name: Build iOS IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install depot_tools
      run: |
        ls /Applications/Xcode_16.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.2.sdk/System/Library/Frameworks/BrowserEngineCore.framework/Headers
        exit 1
        cd $HOME
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo ":$HOME/depot_tools:$HOME/depot_tools/python-bin" >> $GITHUB_PATH

    - name: Fetch Chromium Source
      run: |
        cd $HOME
        mkdir -p ~/chromium && cd ~/chromium
        fetch --no-history ios 
        cd src
        sed -i '' 's/26.0/18.0/g' ./build/config/ios/ios_sdk_overrides.gni
        cat ./build/config/ios/ios_sdk_overrides.gni
        gclient sync

    - name: Generate Build Files
      run: |
        cd ~/chromium/src && mkdir -p out/Release-iphoneos
        gn gen out/Release-iphoneos --args='is_debug=false target_os="ios" ios_enable_code_signing=false ios_min_target="18.0" is_component_build=false target_environment="device" target_cpu="arm64" use_blink=true'

    - name: Build Chromium for iOS
      continue-on-error: true
      run: |
        cd ~/chromium/src
        autoninja -C out/Release-iphoneos chrome

    - name: Create .ipa File
      run: |
        cd ~/chromium/src/out/Release-iphoneos
        mkdir -p Payload
        cp -r chromium.app Payload/
        zip -r chromium.ipa Payload
        zip -r everything.zip siso_output siso.INFO siso_failed_commands.sh 

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: ~/chromium/src/out/Release-iphoneos/chromium.ipa

    - name: Upload Everything
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: ~/chromium/src/out/Release-iphoneos/everything.zip
